version: "3.8"

services:
  mysql:
    image: mysql:8
    env_file:
      - .env
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    env_file:
      - .env
    command: >
      sh -c "
      pnpm prisma generate &&
      pnpm start:prod
      "
    volumes:
      - ./backend:/app
      - /app/node_modules

volumes:
  mysql-data:
