FROM node:18-alpine as build
WORKDIR /app
RUN yarn --quiet --no-optional --no-fund --loglevel=error
RUN npx prisma generate
COPY package.json .
COPY yarn.lock .
COPY src ./src
COPY tsconfig.json .
COPY nest-cli.json .
FROM node:18-alpine 
WORKDIR /app
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/src ./src
COPY package.json .
COPY tsconfig.json .
EXPOSE 3000
CMD ["yarn","start"]